export type MusicStyleTemplateDefinition = {
  categoryId: string;
  categoryName: string;
  categoryOrder: number;
  styleName: string;
  styleLabel: string;
  summary: string;
  positioning: string;
  genre: string;
  mood: string;
  bpm: string;
  harmony: string;
  vocals: string;
  instruments: string;
  mix: string;
  banned: string;
};

export type MusicStyleTemplate = MusicStyleTemplateDefinition & {
  id: string;
  prompt: string;
  createdAt: string;
  updatedAt: string;
};

export type MusicStyleTemplateGroup = {
  categoryId: string;
  categoryName: string;
  categoryOrder: number;
  templates: MusicStyleTemplate[];
};

const templateDefinitions: MusicStyleTemplateDefinition[] = [
  {
    categoryId: "pop",
    categoryName: "泛 Pop 流行",
    categoryOrder: 1,
    styleName: "Modern Pop",
    styleLabel: "现代商业流行",
    summary: "主流平台传播感强，抓耳、明亮、完成度高。",
    positioning: "适合主流平台传播的高完成度商业流行单曲。",
    genre: "Modern Pop, 2020s contemporary radio pop.",
    mood: "明亮、真诚、积极，带一点情绪张力。",
    bpm: "100–116 BPM，中速律动。",
    harmony: "大调或明亮小调，流行四和弦走向，副歌抓耳。",
    vocals: "英语女声，清晰靠前，主歌亲密自然，副歌明亮有爆发力，加入宽阔和声叠唱。",
    instruments: "电子鼓、合成器铺底、干净电吉他、Sub Bass、钢琴点缀、Hook 合成器。",
    mix: "Radio-ready commercial mix, upfront vocal, tight low end, glossy synth layers, wide stereo image, polished master.",
    banned: "No rap verse, no EDM drop, no harsh distortion, no robotic vocal, no excessive autotune.",
  },
  {
    categoryId: "pop",
    categoryName: "泛 Pop 流行",
    categoryOrder: 1,
    styleName: "Synth Pop",
    styleLabel: "合成器流行",
    summary: "复古霓虹、都市夜晚、梦幻又带冷感。",
    positioning: "适合都市夜晚、科技感、复古霓虹、情绪化品牌内容。",
    genre: "Synth Pop, 1980s-inspired with modern 2020s production.",
    mood: "浪漫、梦幻、怀旧、冷感都市。",
    bpm: "92–110 BPM，稳定中速律动。",
    harmony: "小调为主，副歌转向更明亮的大和弦，带复古流行色彩。",
    vocals: "英语男声，温暖低中音，主歌克制，副歌加入延迟感和宽阔叠唱。",
    instruments: "Analog synth pads、Arpeggiated synths、Gated drums、Deep bass、Electric piano、Lead synth。",
    mix: "Wide stereo synth field, warm analog texture, clean vocal, spacious reverb, smooth compression.",
    banned: "No heavy rock guitars, no trap hi-hats, no aggressive dubstep bass, no lo-fi muddy mix.",
  },
  {
    categoryId: "pop",
    categoryName: "泛 Pop 流行",
    categoryOrder: 1,
    styleName: "Dance Pop",
    styleLabel: "舞曲流行",
    summary: "适合短视频、派对和健身的高能量流行舞曲。",
    positioning: "适合短视频、派对、健身、时尚活动的轻快流行舞曲。",
    genre: "Dance Pop, 2010s–2020s club-friendly pop.",
    mood: "自信、兴奋、轻松、充满能量。",
    bpm: "118–126 BPM，四拍律动。",
    harmony: "大调或明亮小调，和声简单直接，突出 Hook 重复性。",
    vocals: "英语女声，明亮有力量，副歌加入多人和声、切片人声或呼喊式 Hook。",
    instruments: "Four-on-the-floor kick、Punchy claps、Pluck synths、Sidechain bass、Bright pads、Vocal chops。",
    mix: "Club-ready but clean, punchy drums, tight bass, bright high end, strong sidechain groove.",
    banned: "No dark cinematic mood, no slow ballad arrangement, no acoustic-only production, no messy over-layering.",
  },
  {
    categoryId: "pop",
    categoryName: "泛 Pop 流行",
    categoryOrder: 1,
    styleName: "Pop Rock",
    styleLabel: "流行摇滚",
    summary: "青春、励志、成长感很强，适合大开大合副歌。",
    positioning: "适合青春、励志、校园、运动或成长主题的流行摇滚。",
    genre: "Pop Rock, 2000s–2020s mainstream guitar pop.",
    mood: "热血、真诚、青春、向上。",
    bpm: "120–150 BPM，中快板。",
    harmony: "大调或明亮小调，Power chord 推进，副歌大开大合。",
    vocals: "英语男声，年轻有力量，略带颗粒感，主歌自然，副歌高能量演唱，加入群唱和声。",
    instruments: "Electric guitars、Live drums、Bass guitar、Power chords、Clean verse guitar、Big chorus guitars。",
    mix: "Energetic full-band mix, punchy live drums, upfront vocal, wide guitars, clean but powerful rock master.",
    banned: "No metal screaming, no extreme distortion, no EDM drop, no trap beat, no overly synthetic drums.",
  },
  {
    categoryId: "pop",
    categoryName: "泛 Pop 流行",
    categoryOrder: 1,
    styleName: "Indie Pop",
    styleLabel: "独立流行",
    summary: "松弛、温柔、轻微忧郁，适合生活方式和文艺内容。",
    positioning: "适合小众审美、生活方式、文艺短片或轻剧情内容。",
    genre: "Indie Pop, 2010s–2020s bedroom pop / alternative pop.",
    mood: "松弛、温柔、轻微忧郁、自然真实。",
    bpm: "78–100 BPM，中慢速或轻摇摆律动。",
    harmony: "柔和小调或暖色大调，加入七和弦、挂留和弦。",
    vocals: "英语女声，自然亲密，轻微气声，不炫技，保留一点真实瑕疵感。",
    instruments: "Clean electric guitar、Soft synth pad、Simple drums、Warm bass、Lo-fi keyboard、Subtle percussion。",
    mix: "Warm intimate mix, slightly vintage texture, soft compression, natural room reverb, not overly polished.",
    banned: "No stadium anthem, no heavy EDM elements, no exaggerated vocal runs, no overly glossy commercial pop sound.",
  },
  {
    categoryId: "cantopop",
    categoryName: "粤语流行 Cantopop",
    categoryOrder: 2,
    styleName: "Classic Cantopop Ballad",
    styleLabel: "经典港式情歌",
    summary: "怀旧深情，最像经典港乐抒情单曲。",
    positioning: "适合深情、怀旧、都市爱情主题的粤语抒情歌。",
    genre: "Cantopop ballad, 1980s–1990s Hong Kong classic pop.",
    mood: "深情、克制、怀旧、略带遗憾。",
    bpm: "68–78 BPM，慢板抒情。",
    harmony: "小调为主，副歌可转向更明亮的大和弦，经典港乐递进。",
    vocals: "粤语男声，成熟温暖，中低音厚实，主歌内敛叙事，副歌深情拉开，带自然颤音。",
    instruments: "钢琴、弦乐组、原声吉他、电贝斯、轻柔鼓组、复古合成器铺底。",
    mix: "Warm classic pop mix, upfront vocal, lush strings, smooth reverb, nostalgic analog texture.",
    banned: "No EDM drop, no trap beat, no rap verse, no robotic vocal, no excessive autotune.",
  },
  {
    categoryId: "cantopop",
    categoryName: "粤语流行 Cantopop",
    categoryOrder: 2,
    styleName: "Urban Cantopop",
    styleLabel: "都市粤语流行",
    summary: "夜景、情感拉扯、都市感很强。",
    positioning: "适合现代都市、夜景、情感拉扯、港风短片。",
    genre: "Modern Cantopop, 2010s–2020s Hong Kong urban pop.",
    mood: "冷静、暧昧、孤独、都市感。",
    bpm: "82–96 BPM，中慢速律动。",
    harmony: "小调或灰色大调，加入 R&B 七和弦与流行和声。",
    vocals: "粤语女声，细腻有气声，主歌贴耳，副歌情绪逐渐打开，加入柔和叠唱。",
    instruments: "Electric piano、Clean electric guitar、Sub bass、Soft drums、Ambient pads、Minimal synth textures。",
    mix: "Modern polished urban mix, intimate vocal, deep warm low end, spacious reverb, smooth high frequencies.",
    banned: "No heavy rock guitars, no festival EDM drop, no exaggerated vocal runs, no muddy low end.",
  },
  {
    categoryId: "cantopop",
    categoryName: "粤语流行 Cantopop",
    categoryOrder: 2,
    styleName: "Bright Cantopop",
    styleLabel: "港式轻快流行",
    summary: "明亮甜美，适合恋爱、广告和生活方式内容。",
    positioning: "适合轻松、恋爱、生活方式、广告短视频。",
    genre: "Bright Cantopop, 2000s–2020s mainstream Hong Kong pop.",
    mood: "轻快、甜美、阳光、亲切。",
    bpm: "100–118 BPM，中快板。",
    harmony: "大调为主，和声简单明亮，副歌旋律抓耳。",
    vocals: "粤语女声，清亮甜美，发音自然，主歌轻松，副歌明亮有笑意，加入清爽和声。",
    instruments: "Acoustic guitar、Clean guitar、Pop drums、Bass、Bright piano、Handclaps、Light synth。",
    mix: "Clean radio pop mix, bright vocal, tight drums, warm guitars, polished commercial master.",
    banned: "No dark trap atmosphere, no heavy distortion, no slow cinematic mood, no overly synthetic vocal.",
  },
  {
    categoryId: "cantopop",
    categoryName: "粤语流行 Cantopop",
    categoryOrder: 2,
    styleName: "Cantonese R&B Ballad",
    styleLabel: "粤语 R&B 情歌",
    summary: "深夜、暧昧、丝滑和声，带 Neo-soul 气质。",
    positioning: "适合暧昧、深夜、情绪独白、都市爱情。",
    genre: "Cantonese R&B, 2000s–2020s smooth pop R&B.",
    mood: "细腻、性感、克制、微伤感。",
    bpm: "70–88 BPM，慢中速 Groove。",
    harmony: "小调、七和弦、九和弦，和声柔滑，有 Neo-soul 色彩。",
    vocals: "粤语男声，柔和中高音，带轻微气声和自然转音，副歌加入多层和声。",
    instruments: "Rhodes electric piano、Soft drum groove、Deep bass、Clean guitar、Warm pads、Subtle percussion。",
    mix: "Smooth R&B mix, silky upfront vocal, warm low end, soft compression, spacious late-night reverb.",
    banned: "No aggressive rap, no EDM drop, no rock distortion, no over-autotune, no harsh bright mix.",
  },
  {
    categoryId: "cantopop",
    categoryName: "粤语流行 Cantopop",
    categoryOrder: 2,
    styleName: "Cantopop Rock",
    styleLabel: "粤语摇滚流行",
    summary: "热血、真诚、适合青春成长和剧情推进。",
    positioning: "适合青春、成长、励志、港风热血剧情。",
    genre: "Cantopop Rock, 1990s–2020s Hong Kong pop rock.",
    mood: "真诚、热血、怀旧、带情绪释放。",
    bpm: "110–135 BPM，中快板。",
    harmony: "大调或明亮小调，Power chord 推进，副歌大开大合。",
    vocals: "粤语男声，年轻有力量，略带沙哑颗粒感，主歌叙事，副歌高亢开阔。",
    instruments: "Electric guitars、Live drums、Bass guitar、Piano accents、Backing vocals、Light strings in final chorus。",
    mix: "Energetic band mix, wide guitars, punchy live drums, clear vocal, polished pop-rock master.",
    banned: "No metal screaming, no trap 808, no EDM build-up, no overly glossy dance-pop synths.",
  },
  {
    categoryId: "mandopop",
    categoryName: "国语流行 Mandopop",
    categoryOrder: 3,
    styleName: "Modern Mandopop Ballad",
    styleLabel: "现代国语情歌",
    summary: "失恋、共鸣、短视频传播都很稳。",
    positioning: "适合爱情、失恋、情绪共鸣、短视频传播的国语抒情歌。",
    genre: "Modern Mandopop ballad, 2010s–2020s Chinese pop.",
    mood: "深情、温柔、遗憾，情绪递进明显。",
    bpm: "70–84 BPM，慢板到中慢板。",
    harmony: "小调为主，副歌旋律上扬，和声流畅易唱。",
    vocals: "国语男声，温暖细腻，主歌贴耳克制，副歌情绪爆发但保持自然，不要过度炫技。",
    instruments: "钢琴、弦乐、原声吉他、柔和鼓组、贝斯、氛围 Pad。",
    mix: "Polished Mandopop ballad mix, clear upfront vocal, warm piano, lush strings, spacious reverb.",
    banned: "No rap verse, no EDM drop, no robotic vocal, no heavy rock distortion, no excessive autotune.",
  },
  {
    categoryId: "mandopop",
    categoryName: "国语流行 Mandopop",
    categoryOrder: 3,
    styleName: "Mandopop R&B",
    styleLabel: "国语流行 R&B",
    summary: "都市夜晚、暧昧关系、松弛感很强。",
    positioning: "适合都市情感、夜晚氛围、暧昧关系、年轻用户。",
    genre: "Mandopop R&B, 2000s–2020s Chinese urban pop.",
    mood: "细腻、松弛、暧昧，带一点孤独感。",
    bpm: "76–92 BPM，中慢速 Groove。",
    harmony: "小调或暖色大调，七和弦、九和弦，和声柔滑。",
    vocals: "国语女声，气声细腻，主歌近距离耳语感，副歌加入丝滑转音和多层和声。",
    instruments: "Electric piano、Clean guitar、Sub bass、Soft R&B drums、Warm pad、Finger snaps。",
    mix: "Smooth modern R&B mix, intimate vocal, deep bass, soft high end, warm reverb, polished urban texture.",
    banned: "No aggressive trap rap, no EDM drop, no heavy guitars, no harsh vocal tuning.",
  },
  {
    categoryId: "mandopop",
    categoryName: "国语流行 Mandopop",
    categoryOrder: 3,
    styleName: "Youth Mandopop",
    styleLabel: "青春国语流行",
    summary: "校园、成长、甜蜜恋爱和短剧主题曲都合适。",
    positioning: "适合校园、青春、成长、甜蜜恋爱、短剧主题曲。",
    genre: "Youth Mandopop, 2000s–2020s Chinese pop.",
    mood: "清新、阳光、真诚、轻微心动感。",
    bpm: "92–112 BPM，中速轻快。",
    harmony: "大调为主，和声明亮简单，副歌旋律易记。",
    vocals: "国语女声，清亮自然，年轻感强，主歌轻柔，副歌明亮甜美，加入轻快和声。",
    instruments: "Acoustic guitar、Bright piano、Light drums、Bass、Clean electric guitar、Handclaps、Soft strings。",
    mix: "Fresh clean pop mix, bright vocal, warm acoustic texture, balanced drums, radio-friendly polish.",
    banned: "No dark cinematic mood, no trap 808, no heavy distortion, no overly mature dramatic vocal.",
  },
  {
    categoryId: "mandopop",
    categoryName: "国语流行 Mandopop",
    categoryOrder: 3,
    styleName: "Mandopop Rock",
    styleLabel: "国语摇滚流行",
    summary: "适合励志、告别、人生阶段与成长叙事。",
    positioning: "适合励志、成长、热血、告别、人生阶段主题。",
    genre: "Mandopop Rock, 2000s–2020s Chinese pop rock.",
    mood: "坚定、热血、真诚、情绪释放。",
    bpm: "105–135 BPM，中快板。",
    harmony: "大调或明亮小调，吉他和弦推动，副歌具有合唱感。",
    vocals: "国语男声，清晰有力量，略带颗粒感，主歌叙事，副歌高能量演唱，适合群唱和声。",
    instruments: "Electric guitars、Live drums、Bass guitar、Piano、Power chords、Backing vocals。",
    mix: "Modern pop-rock mix, punchy drums, wide guitars, upfront vocal, clean but powerful master.",
    banned: "No metal growling, no trap beat, no EDM drop, no overly soft acoustic-only arrangement.",
  },
  {
    categoryId: "mandopop",
    categoryName: "国语流行 Mandopop",
    categoryOrder: 3,
    styleName: "Chinese Style Mandopop",
    styleLabel: "国风国语流行",
    summary: "东方美学、影视感、古风叙事都能套。",
    positioning: "适合古风、国风、影视感、东方美学、文化类内容。",
    genre: "Chinese-style Mandopop, 2000s–2020s oriental pop fusion.",
    mood: "诗意、婉转、唯美，带古典叙事感。",
    bpm: "72–96 BPM，中慢速或中速。",
    harmony: "五声音阶色彩，小调或宫调式氛围，融合流行和东方旋律感。",
    vocals: "国语女声，柔美清亮，咬字清晰，主歌含蓄，副歌婉转开阔，可加入轻柔和声。",
    instruments: "古筝、琵琶、笛子、钢琴、弦乐、低鼓、现代流行鼓组、Ambient pad。",
    mix: "Elegant cinematic pop mix, clear vocal, blend of traditional instruments and modern production, spacious reverb.",
    banned: "No EDM festival drop, no trap hi-hats, no heavy rock guitars, no parody oriental sound, no robotic vocal.",
  },
  {
    categoryId: "hiphop",
    categoryName: "Hip-Hop / R&B",
    categoryOrder: 4,
    styleName: "Trap",
    styleLabel: "陷阱嘻哈",
    summary: "暗黑、高压、潮流感强，适合运动和游戏内容。",
    positioning: "适合潮流、街头、运动、游戏或高能短视频。",
    genre: "Trap, 2010s–2020s modern hip-hop.",
    mood: "冷酷、自信、压迫感、暗黑高级。",
    bpm: "130–150 BPM，Half-time feel。",
    harmony: "小调、暗色和声、重复性旋律动机。",
    vocals: "英语男声，低沉冷感，Flow 稳定，副歌有重复 Hook，可带少量旋律化说唱。",
    instruments: "808 bass、Trap hi-hats、Snappy snare、Dark piano loop、Bell melody、Atmospheric pads。",
    mix: "Hard-hitting low end, crisp hi-hats, spacious dark atmosphere, clean vocal processing.",
    banned: "No acoustic ballad style, no bright bubblegum pop, no live jazz swing, no distorted clipping master.",
  },
  {
    categoryId: "hiphop",
    categoryName: "Hip-Hop / R&B",
    categoryOrder: 4,
    styleName: "Melodic Rap",
    styleLabel: "旋律说唱",
    summary: "情绪化、夜晚独白、年轻用户会很买账。",
    positioning: "适合情绪表达、年轻用户、夜晚独白、情感故事。",
    genre: "Melodic Rap, late 2010s–2020s emotional hip-hop.",
    mood: "孤独、真诚、伤感但有力量。",
    bpm: "70–90 BPM 或 140–180 BPM half-time。",
    harmony: "小调为主，和弦循环感强，旋律简单上口。",
    vocals: "国语男声，带旋律感的说唱人声，轻微 Auto-Tune 色彩，副歌更歌唱化，情绪靠前。",
    instruments: "808 bass、Soft guitar loop、Mellow keys、Trap drums、Ambient pad、Sparse percussion。",
    mix: "Emotional modern rap mix, upfront processed vocal, deep sub bass, airy reverb, clean but intimate.",
    banned: "No aggressive shouting, no boom bap scratches, no EDM festival drop, no overly clean pop vocal.",
  },
  {
    categoryId: "hiphop",
    categoryName: "Hip-Hop / R&B",
    categoryOrder: 4,
    styleName: "Boom Bap",
    styleLabel: "经典嘻哈",
    summary: "复古街头、纪录片感、文化表达很稳。",
    positioning: "适合街头叙事、复古潮流、纪录片感或文化表达。",
    genre: "Boom Bap, 1990s East Coast hip-hop inspired.",
    mood: "真实、冷静、复古、街头感。",
    bpm: "86–96 BPM，稳定重拍。",
    harmony: "小调或爵士采样感和声，循环段落感强。",
    vocals: "英语男声，自然说唱人声，Flow 清晰有节奏，副歌可加入简单 Hook 或采样式和声。",
    instruments: "Dusty drum break、Vinyl sample texture、Jazz piano loop、Upright bass、Scratch accents、Brass stabs。",
    mix: "Warm dusty mix, punchy sampled drums, vinyl texture, dry vocal, vintage compression.",
    banned: "No trap hi-hat rolls, no glossy dance-pop synths, no heavy autotune, no EDM build-up.",
  },
  {
    categoryId: "hiphop",
    categoryName: "Hip-Hop / R&B",
    categoryOrder: 4,
    styleName: "Contemporary R&B",
    styleLabel: "现代 R&B",
    summary: "性感、温柔、夜晚氛围，适合高级感内容。",
    positioning: "适合情感、夜晚、亲密关系、都市高级感内容。",
    genre: "Contemporary R&B, 2010s–2020s smooth R&B.",
    mood: "性感、温柔、克制、细腻。",
    bpm: "68–92 BPM，慢中速律动。",
    harmony: "小调、七和弦、九和弦、Neo-soul 色彩。",
    vocals: "英语女声，柔和细腻，气声主歌，副歌加入丝滑转音与多层和声。",
    instruments: "Electric piano、Deep bass、Soft drums、Warm pad、Clean guitar、Subtle percussion。",
    mix: "Smooth polished R&B mix, silky vocal, warm low end, spacious reverb, soft high frequencies.",
    banned: "No rock guitars, no aggressive rap shouting, no EDM drop, no harsh bright mix.",
  },
  {
    categoryId: "hiphop",
    categoryName: "Hip-Hop / R&B",
    categoryOrder: 4,
    styleName: "Neo Soul",
    styleLabel: "新灵魂乐",
    summary: "复古、温暖、有灵魂感，适合咖啡馆和艺术内容。",
    positioning: "适合高级、复古、艺术感、咖啡馆、生活方式品牌内容。",
    genre: "Neo Soul, late 1990s–2020s organic soul.",
    mood: "慵懒、温暖、成熟、富有灵魂感。",
    bpm: "72–92 BPM，Swing groove。",
    harmony: "复杂延伸和弦，七和弦、九和弦、十一和弦，爵士化和声。",
    vocals: "英语女声，温暖灵魂嗓音，自然转音，细腻即兴感，和声层次丰富但不过度炫技。",
    instruments: "Rhodes piano、Live bass、Brushed drums、Clean guitar、Organ pad、Subtle brass、Background vocals。",
    mix: "Organic warm mix, live-room feel, vintage saturation, smooth vocal blend, soft dynamics.",
    banned: "No trap beat, no synthetic EDM sound, no robotic vocal tuning, no overly quantized drums.",
  },
  {
    categoryId: "rock",
    categoryName: "Rock / Alternative",
    categoryOrder: 5,
    styleName: "Alternative Rock",
    styleLabel: "另类摇滚",
    summary: "压抑、真实、释放，适合片尾和态度表达。",
    positioning: "适合情绪宣泄、青年表达、剧情片尾、品牌态度内容。",
    genre: "Alternative Rock, 1990s–2020s guitar-driven rock.",
    mood: "压抑、真实、释放、略带反叛。",
    bpm: "95–130 BPM，中速到中快。",
    harmony: "小调或灰色大调，强调情绪张力。",
    vocals: "英语男声，自然有颗粒感，主歌内敛，副歌爆发，保留一点粗粝感。",
    instruments: "Distorted electric guitars、Live drums、Bass guitar、Clean verse guitar、Feedback textures。",
    mix: "Raw but polished band mix, wide guitars, punchy drums, upfront emotional vocal, natural room energy.",
    banned: "No EDM drop, no trap beat, no overly glossy pop vocal, no metal screaming.",
  },
  {
    categoryId: "rock",
    categoryName: "Rock / Alternative",
    categoryOrder: 5,
    styleName: "Indie Rock",
    styleLabel: "独立摇滚",
    summary: "文艺、城市、轻微不完美的现场感。",
    positioning: "适合文艺、城市、生活方式、年轻态度、轻剧情内容。",
    genre: "Indie Rock, 2000s–2020s alternative indie band sound.",
    mood: "自由、松弛、微酸、真实。",
    bpm: "100–140 BPM，轻快或中速摇摆。",
    harmony: "大调、小调均可，吉他和弦循环，带一点不完美的现场感。",
    vocals: "英语女声，自然不炫技，轻微鼻音或颗粒感，副歌可加入群唱。",
    instruments: "Jangly guitars、Live drums、Bass guitar、Vintage keyboard、Handclaps、Simple backing vocals。",
    mix: "Organic indie band mix, slightly raw guitars, natural drums, warm midrange, not overly compressed.",
    banned: "No heavy metal distortion, no trap 808, no glossy EDM synths, no overly perfect pop tuning.",
  },
  {
    categoryId: "rock",
    categoryName: "Rock / Alternative",
    categoryOrder: 5,
    styleName: "Pop Punk",
    styleLabel: "流行朋克",
    summary: "青春、冲动、叛逆，适合快节奏短视频。",
    positioning: "适合青春、校园、运动、反叛、快节奏短视频。",
    genre: "Pop Punk, 2000s–2020s energetic punk pop.",
    mood: "青春、冲动、热血、带一点叛逆。",
    bpm: "150–180 BPM，快节奏。",
    harmony: "大调或明亮小调，Power chords，副歌简单直接。",
    vocals: "英语男声，年轻有冲劲，略带喊唱感，副歌多人和声增强感染力。",
    instruments: "Fast live drums、Power chord guitars、Driving bass、Palm-muted verse guitars、Big chorus guitars。",
    mix: "Loud energetic band mix, punchy snare, wide rhythm guitars, clear vocal, tight modern rock master.",
    banned: "No slow ballad tempo, no trap hi-hats, no EDM drop, no overly soft acoustic arrangement.",
  },
  {
    categoryId: "rock",
    categoryName: "Rock / Alternative",
    categoryOrder: 5,
    styleName: "Hard Rock",
    styleLabel: "硬摇滚",
    summary: "燃、重、适合动作和力量感内容。",
    positioning: "适合燃向、动作、赛车、游戏、极限运动、力量型品牌内容。",
    genre: "Hard Rock, 1980s–2020s modern heavy guitar rock.",
    mood: "强悍、燃烧、压迫、充满力量。",
    bpm: "110–150 BPM，中快板，Riff 驱动。",
    harmony: "小调或五声音阶感，Power chords，Riff 重复带冲击力。",
    vocals: "英语男声，力量型嗓音，略带沙哑，副歌高亢但不极端嘶吼。",
    instruments: "Heavy electric guitar riffs、Live drums、Bass guitar、Cymbal crashes、Guitar solo accents。",
    mix: "Powerful modern rock mix, thick guitars, punchy drums, strong bass, aggressive but clear master.",
    banned: "No death metal growling, no EDM synth drop, no soft folk mood, no thin guitar tone.",
  },
  {
    categoryId: "rock",
    categoryName: "Rock / Alternative",
    categoryOrder: 5,
    styleName: "Acoustic Rock",
    styleLabel: "原声摇滚",
    summary: "真诚、温暖、适合公路和成长叙事。",
    positioning: "适合公路、成长、情感叙事、纪录片、真诚品牌表达。",
    genre: "Acoustic Rock, 1990s–2020s singer-songwriter rock.",
    mood: "真诚、温暖、坚定、略带沧桑。",
    bpm: "78–105 BPM，中慢速。",
    harmony: "大调或暖色小调，和弦自然流畅，副歌有抬升感。",
    vocals: "英语男声，温暖自然，主歌叙事感，副歌更开阔，可加入轻微和声。",
    instruments: "Acoustic guitar、Light electric guitar、Live drums、Bass guitar、Piano、Subtle strings。",
    mix: "Warm organic mix, natural room ambience, clear vocal, balanced guitars, gentle compression.",
    banned: "No heavy metal distortion, no trap beat, no EDM drop, no over-processed vocal.",
  },
  {
    categoryId: "folk",
    categoryName: "Folk / Cinematic / World",
    categoryOrder: 6,
    styleName: "Indie Folk",
    styleLabel: "独立民谣",
    summary: "安静、温柔、适合旅行和纪录片。",
    positioning: "适合旅行、自然、生活方式、纪录片、温柔叙事。",
    genre: "Indie Folk, 2000s–2020s acoustic singer-songwriter.",
    mood: "安静、温柔、怀旧、真挚。",
    bpm: "70–95 BPM，中慢速。",
    harmony: "大调或柔和小调，开放和弦，旋律自然流动。",
    vocals: "英语女声，亲密自然，轻声演唱，保留呼吸感和真实情绪。",
    instruments: "Acoustic guitar fingerpicking、Soft piano、Brushed drums、Upright bass、Subtle strings、Hand percussion。",
    mix: "Warm intimate acoustic mix, natural room sound, soft reverb, organic dynamics, minimal processing.",
    banned: "No EDM drop, no trap drums, no heavy distortion, no glossy pop overproduction.",
  },
  {
    categoryId: "folk",
    categoryName: "Folk / Cinematic / World",
    categoryOrder: 6,
    styleName: "Country Pop",
    styleLabel: "乡村流行",
    summary: "阳光、家庭、公路、积极生活方式。",
    positioning: "适合公路、阳光、成长、家庭、积极生活方式。",
    genre: "Country Pop, 2000s–2020s Nashville-inspired pop country.",
    mood: "温暖、乐观、真诚、开阔。",
    bpm: "90–120 BPM，中速律动。",
    harmony: "大调为主，和声明亮，副歌旋律上扬。",
    vocals: "英语女声，温暖自然，略带乡村口吻，副歌加入清晰和声叠唱。",
    instruments: "Acoustic guitar、Clean electric guitar、Banjo accents、Pedal steel、Live drums、Bass guitar。",
    mix: "Polished Nashville mix, clear vocal, warm guitars, tight live rhythm section, radio-friendly master.",
    banned: "No heavy EDM synths, no trap 808, no dark cinematic mood, no excessive autotune.",
  },
  {
    categoryId: "folk",
    categoryName: "Folk / Cinematic / World",
    categoryOrder: 6,
    styleName: "Cinematic Pop",
    styleLabel: "电影感流行",
    summary: "宏大、感动、适合大片和品牌故事。",
    positioning: "适合广告大片、预告片、品牌故事、励志情绪视频。",
    genre: "Cinematic Pop, 2010s–2020s orchestral pop production.",
    mood: "宏大、感动、希望、史诗感。",
    bpm: "72–96 BPM，中慢速，逐步推进。",
    harmony: "小调起步，副歌转向明亮或希望感和声，具有情绪递进。",
    vocals: "英语女声，情绪细腻，主歌克制，副歌宽广有力量，加入大气和声层。",
    instruments: "Piano、Orchestral strings、Cinematic percussion、Ambient pads、Deep bass、Soft guitars、Choir-like backing vocals。",
    mix: "Huge cinematic mix, wide stereo image, lush reverb, clear vocal, dramatic dynamics, polished master.",
    banned: "No club EDM drop, no trap hi-hats, no comedy mood, no thin small arrangement.",
  },
  {
    categoryId: "folk",
    categoryName: "Folk / Cinematic / World",
    categoryOrder: 6,
    styleName: "Afrobeat / Afropop",
    styleLabel: "非洲流行律动",
    summary: "夏日、舞蹈、旅行、轻松社交都很合适。",
    positioning: "适合夏日、舞蹈、旅行、轻松社交、活力品牌内容。",
    genre: "Afrobeat / Afropop, 2010s–2020s global pop fusion.",
    mood: "阳光、松弛、性感、快乐。",
    bpm: "95–115 BPM，切分律动明显。",
    harmony: "大调或轻快小调，和声循环，强调 Groove 和 Hook。",
    vocals: "英语男声，轻松有节奏感，短句 Hook，加入呼应式和声与群唱。",
    instruments: "Afro percussion、Syncopated drums、Warm bass、Clean guitar riffs、Marimba or pluck synth、Light pads。",
    mix: "Bright rhythmic mix, punchy percussion, warm low end, clean vocal, spacious tropical atmosphere.",
    banned: "No heavy rock guitars, no dark trap atmosphere, no slow ballad arrangement, no overly dense orchestration.",
  },
  {
    categoryId: "folk",
    categoryName: "Folk / Cinematic / World",
    categoryOrder: 6,
    styleName: "Latin Pop",
    styleLabel: "拉丁流行",
    summary: "热情、浪漫、性感，适合派对和度假内容。",
    positioning: "适合舞蹈、热情、度假、派对、时尚和短视频传播。",
    genre: "Latin Pop, 2000s–2020s global Latin pop.",
    mood: "热情、浪漫、性感、明亮。",
    bpm: "92–120 BPM，拉丁律动。",
    harmony: "大调或浪漫小调，和声简单上口，副歌旋律强记忆点。",
    vocals: "西班牙语女声，热情明亮，主歌有律动感，副歌开放有感染力，可加入呼应式和声。",
    instruments: "Nylon guitar、Latin percussion、Reggaeton-inspired drums、Warm bass、Brass accents、Rhythmic piano or synth plucks。",
    mix: "Polished global pop mix, punchy percussion, warm bass, bright vocal, danceable stereo groove.",
    banned: "No heavy metal guitars, no slow cinematic ballad feel, no muddy percussion, no robotic vocal.",
  },
];

function now() {
  return new Date().toISOString();
}

export function buildStyleTemplatePrompt(template: MusicStyleTemplateDefinition) {
  return [
    `【${template.categoryName}｜${template.styleLabel}】`,
    `风格：${template.styleName}`,
    `歌曲定位：${template.positioning}`,
    `流派/年代：${template.genre}`,
    `情绪：${template.mood}`,
    `节奏/BPM：${template.bpm}`,
    `调性/和声感：${template.harmony}`,
    `人声设定：${template.vocals}`,
    `编曲乐器：${template.instruments}`,
    `制作/混音质感：${template.mix}`,
    `禁止项：${template.banned}`,
  ].join("\n");
}

export function createMusicStyleTemplates(timestamp = now()) {
  return templateDefinitions.map((template, index) => ({
    ...template,
    id: `style-template-${template.categoryId}-${String(index + 1).padStart(2, "0")}`,
    prompt: buildStyleTemplatePrompt(template),
    createdAt: timestamp,
    updatedAt: timestamp,
  }));
}

export function appendStyleTemplatePrompt(currentPrompt: string, templatePrompt: string) {
  const trimmedPrompt = currentPrompt.trim();
  const trimmedTemplate = templatePrompt.trim();

  if (!trimmedPrompt) {
    return trimmedTemplate;
  }

  return `${trimmedPrompt}\n\n${trimmedTemplate}`;
}

export function groupStyleTemplatesByCategory(templates: MusicStyleTemplate[]) {
  const grouped = new Map<string, MusicStyleTemplateGroup>();

  for (const template of templates) {
    const existing = grouped.get(template.categoryId);

    if (existing) {
      existing.templates.push(template);
      continue;
    }

    grouped.set(template.categoryId, {
      categoryId: template.categoryId,
      categoryName: template.categoryName,
      categoryOrder: template.categoryOrder,
      templates: [template],
    });
  }

  return [...grouped.values()]
    .sort((left, right) => left.categoryOrder - right.categoryOrder)
    .map((group) => ({
      ...group,
      templates: [...group.templates].sort((left, right) =>
        left.id.localeCompare(right.id),
      ),
    }));
}

